steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/maptool', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/maptool' ]
images: ['europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/maptool']
options:
  logging: CLOUD_LOGGING_ONLY
